package com.mycompany.projekt.db;
// Generated 2016-11-29 19:53:26 by Hibernate Tools 3.6.0




/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private int orderId;
     private Menu menu;
     private UserDb userDb;

    public Orders() {
    }

    public Orders(Menu menu, UserDb userDb) {
       this.menu = menu;
       this.userDb = userDb;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    public UserDb getUserDb() {
        return this.userDb;
    }
    
    public void setUserDb(UserDb userDb) {
        this.userDb = userDb;
    }


}


